name: PHP Linter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  php-linter:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      -   name: Setup PHP
          uses: shivammathur/setup-php@c77c69f5c8897d89fe313f4b6dd4d768d6a1b3db # v2
          with:
            php-version: 7.4
            coverage: none # disable xdebug, pcov

      -   name: Composer install
          uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4
          with:
            composer-options: --ansi --prefer-dist

      -   name: Lint PHP
          run: vendor/bin/parallel-lint src tests config
